### ISSUE TITLE
The similar_impl_tensorflow branch doesn't run well

### ISSUE THREAD

**Issue by empty-id** [Diego999/pyGAT#32]
```bash
Loading cora dataset...
Traceback (most recent call last):
  File "train.py", line 105, in <module>
    loss_values.append(train(epoch))
  File "train.py", line 79, in train
    'loss_train: {:.4f}'.format(loss_train.data[0]),
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number
```

I am curious about the 1 minute running time version, so I want to get this branch working.

**Comment by empty-id** [comment]
Solved after I downgrade the torch into 0.4.1
